port: 7890
socks-port: 7891
allow-lan: true
ipv6: false
mode: Rule
log-level: info
tcp-concurrent: true
dns:
  # 开启Clash内置DNS服务器
  enable: true
  # 开启模式fake-ip
  enhanced-mode: fake-ip
  listen: 0.0.0.0:9053
  fake-ip-range: 12.0.0.0/24
proxies:
  - {name: CF:104.19.123.20, server: 104.19.123.20, port: 80, type: vless, uuid: 2e632913-bae0-4855-893c-02c828c835a2, tls: false, network: ws, ws-opts: {path: '/?ed=2048', headers: {Host: worker-calm-rice-56e5.hebe061103.workers.dev}}}
  - {name: CF:172.64.172.17, server: 172.64.172.17, port: 80, type: vless, uuid: 3ada7b0b-4734-448f-adc6-b88a40f65518, tls: false, network: ws, ws-opts: {path: '/?ed=2048', headers: {Host: worker-dark-breeze-d0d7.hebe061103.workers.dev}}}
  - {name: CF:104.19.106.5, server: 104.19.106.5, port: 80, type: vless, uuid: 27b9fc10-48a1-42e4-aef1-aef97860fa3a, tls: false, network: ws, ws-opts: {path: '/?ed=2048', headers: {Host: hello-world-noisy-feather-0a79.hebe061103.workers.dev}}}
  - {name: CF:104.19.106.76, server: 104.19.106.76, port: 80, type: vless, uuid: efe6c33a-5bb7-4aa6-aa79-ad43fe7f86ad, tls: false, network: ws, ws-opts: {path: '/?ed=2048', headers: {Host: hello-world-wild-wave-7a34.hebe061103.workers.dev}}}
  - {name: CF:172.64.172.82, server: 172.64.172.82, port: 80, type: vless, uuid: 0cadcba3-7a09-474d-a4a6-74636407ff19, tls: false, network: ws, ws-opts: {path: '/?ed=2048', headers: {Host: hello-world-proud-voice-9777.hebe061103.workers.dev}}}
  # 以上为代理地址请插入
proxy-groups:
  - name: 🔮 负载均衡
    type: load-balance
    url: http://www.google.com/generate_204
    interval: 300
    strategy: consistent-hashing
    proxies:
      - CF:104.19.123.20
      - CF:172.64.172.17
      - CF:104.19.106.5
      - CF:104.19.106.76
      - CF:172.64.172.82
      # 以上为负载均衡下面的代理地址请插入
rules:
  - MATCH, 🔮 负载均衡
