port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: 0.0.0.0:9090
external-ui: /usr/local/clash/ui
#TCP并发连接将使用所有IP进行TCP握手，并使用最先握手的IP进行后续请求,默认为false
tcp-concurrent: true
# DNS服务器
dns:
  # 开启Clash内置DNS服务器
  # 默认为false
  enable: true
  # 模式fake-ip
  enhanced-mode: fake-ip
  # DNS监听端口
  listen: 0.0.0.0:9053
  fake-ip-range: 12.0.0.1/16
proxies:
  - {name: 峰值速度1| 5750 KB/s, server: 66.235.200.76, port: 80, type: vless, uuid: 2e632913-bae0-4855-893c-02c828c835a2, tls: false, network: ws, ws-opts: {path: '/?ed=2048', headers: {Host: worker-calm-rice-56e5.hebe061103.workers.dev}}}
  - {name: 峰值速度2| 5668 KB/s, server: 64.68.192.87, port: 80, type: vless, uuid: 3ada7b0b-4734-448f-adc6-b88a40f65518, tls: false, network: ws, ws-opts: {path: '/?ed=2048', headers: {Host: worker-dark-breeze-d0d7.hebe061103.workers.dev}}}
  - {name: 峰值速度3| 5724 KB/s, server: 66.235.200.122, port: 80, type: vless, uuid: 27b9fc10-48a1-42e4-aef1-aef97860fa3a, tls: false, network: ws, ws-opts: {path: '/?ed=2048', headers: {Host: hello-world-noisy-feather-0a79.hebe061103.workers.dev}}}
  - {name: 峰值速度4| 5484 KB/s, server: 66.235.200.25, port: 80, type: vless, uuid: efe6c33a-5bb7-4aa6-aa79-ad43fe7f86ad, tls: false, network: ws, ws-opts: {path: '/?ed=2048', headers: {Host: hello-world-wild-wave-7a34.hebe061103.workers.dev}}}
  - {name: 峰值速度5| 5934 KB/s, server: 64.68.192.181, port: 80, type: vless, uuid: 0cadcba3-7a09-474d-a4a6-74636407ff19, tls: false, network: ws, ws-opts: {path: '/?ed=2048', headers: {Host: hello-world-proud-voice-9777.hebe061103.workers.dev}}}
  # 以上为代理地址请插入
proxy-groups:
  - name: 🚀 节点选择
    type: select
    proxies:
      - ♻️  自动选择
      - ⚖️  负载均衡-轮询
      - ⚖️  负载均衡-散列
      - 峰值速度1| 5750 KB/s
      - 峰值速度2| 5668 KB/s
      - 峰值速度3| 5724 KB/s
      - 峰值速度4| 5484 KB/s
      - 峰值速度5| 5934 KB/s
      # 以上为节点选择组的自动选择代理请插入
  - name: ♻️  自动选择
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - 峰值速度1| 5750 KB/s
      - 峰值速度2| 5668 KB/s
      - 峰值速度3| 5724 KB/s
      - 峰值速度4| 5484 KB/s
      - 峰值速度5| 5934 KB/s
      # 以上为自动选择组下面的代理地址请插入
  - name: ⚖️  负载均衡-轮询
    type: load-balance
    url: http://www.google.com/generate_204
    interval: 300
    strategy: round-robin
    proxies:
      - 峰值速度1| 5750 KB/s
      - 峰值速度2| 5668 KB/s
      - 峰值速度3| 5724 KB/s
      - 峰值速度4| 5484 KB/s
      - 峰值速度5| 5934 KB/s
      # 以上为轮询组下面的代理地址请插入
  - name: ⚖️  负载均衡-散列
    type: load-balance
    url: http://www.google.com/generate_204
    interval: 300
    strategy: consistent-hashing
    proxies:
      - 峰值速度1| 5750 KB/s
      - 峰值速度2| 5668 KB/s
      - 峰值速度3| 5724 KB/s
      - 峰值速度4| 5484 KB/s
      - 峰值速度5| 5934 KB/s
      # 以上为散列组下面的代理地址请插入
rules:
 - MATCH,🚀 节点选择
