port: 7890
socks-port: 7891
allow-lan: true
ipv6: false
mode: Rule
log-level: info
tcp-concurrent: true
dns:
  # 开启Clash内置DNS服务器
  enable: true
  # 开启模式fake-ip
  enhanced-mode: fake-ip
  listen: 0.0.0.0:9053
  fake-ip-range: 12.0.0.0/24
proxies:
  - {name: Hong Kong 0, server: 104.17.194.114, port: 80, type: vless, uuid: cdc1d7d3-fe56-4a38-a724-21308e4393d9, tls: false, network: ws, ws-opts: {path: '/?ed=2048', headers: {Host: empty-rain-1b4a.hebe061103.workers.dev}}}
  - {name: Hong Kong 1, server: 104.17.194.18, port: 80, type: vless, uuid: 3d2176d3-89b8-40aa-b004-0ff837bed25c, tls: false, network: ws, ws-opts: {path: '/?ed=2048', headers: {Host: gentle-grass-cf96.hebe061103.workers.dev}}}
  - {name: Hong Kong 2, server: 104.17.194.112, port: 80, type: vless, uuid: 3962565d-e47d-4dd0-aa19-3286e04d9cb6, tls: false, network: ws, ws-opts: {path: '/?ed=2048', headers: {Host: nameless-resonance-6e4c.hebe061103.workers.dev}}}
  - {name: Hong Kong 3, server: 104.17.194.134, port: 80, type: vless, uuid: 4239d44c-19c7-4b8b-ae07-16607c95b6fb, tls: false, network: ws, ws-opts: {path: '/?ed=2048', headers: {Host: gentle-night-12e3.hebe061103.workers.dev}}}
  - {name: Hong Kong 4, server: 104.17.194.43, port: 80, type: vless, uuid: 2e632913-bae0-4855-893c-02c828c835a2, tls: false, network: ws, ws-opts: {path: '/?ed=2048', headers: {Host: 56e5.hebe061103.workers.dev}}}
  # 以上为代理地址请插入
proxy-groups:
  - name: 🔮 负载均衡
    type: load-balance
    url: http://www.google.com/generate_204
    interval: 300
    strategy: consistent-hashing
    proxies:
      - Hong Kong 0
      - Hong Kong 1
      - Hong Kong 2
      - Hong Kong 3
      - Hong Kong 4
      # 以上为负载均衡下面的代理地址请插入
rules:
  - MATCH, 🔮 负载均衡
