#!/bin/bash
rm v2ray.txt
for filename in $(ls cfiplist)
do
  while read line
  do
  let l++
  id=`sed -n "$l p" uuid`
  uuid=${id#*: }
  work=`sed -n "$l p" workershost`
  locate=`sed -n "$l p" iplocate`
  if echo $line | grep "峰值速度";then
  a=${line%:*}
  echo $a
  b=${line#*:}
  echo $b
  line="vless://$uuid@www.visa.com.sg:8880?encryption=none&security=none&type=ws&host=$work&path=/?ed=2560#$work"
  echo $line >>v2ray.txt
  fi
  done < $filename
done
